-- ============================================================================
-- M-Pesa Expense Tracker - PesaDB Initialization Script
-- ============================================================================
-- This script initializes all required tables and seeds default data
-- for the M-Pesa Expense Tracker application using PesaDB.
--
-- IMPORTANT NOTES:
-- 1. PesaDB requires exactly one PRIMARY KEY per table (single column)
-- 2. NO support for AUTO_INCREMENT - use UUIDs generated by application
-- 3. NO support for DEFAULT values - all columns must be provided
-- 4. NO explicit NOT NULL constraint (all columns implicitly required)
-- 5. FOREIGN KEY via REFERENCES is supported
-- 6. Date/time values must be ISO 8601 strings
-- 7. JSON data must be stored as STRING (escaped JSON)
-- 8. NULL is written without quotes for optional values
-- ============================================================================

-- ============================================================================
-- USERS TABLE
-- ============================================================================
-- Stores user accounts with email/password authentication
CREATE TABLE users (
    id STRING PRIMARY KEY,
    email STRING,
    password_hash STRING,
    name STRING,
    created_at STRING,
    preferences STRING
);

-- ============================================================================
-- CATEGORIES TABLE
-- ============================================================================
-- Stores expense/income categories with keywords for auto-categorization
-- user_id can be NULL for default system categories
CREATE TABLE categories (
    id STRING PRIMARY KEY,
    user_id STRING,
    name STRING,
    icon STRING,
    color STRING,
    keywords STRING,
    is_default BOOL
);

-- ============================================================================
-- TRANSACTIONS TABLE
-- ============================================================================
-- Stores all financial transactions (manual and SMS-imported)
-- Includes M-Pesa details and SMS metadata for imported transactions
CREATE TABLE transactions (
    id STRING PRIMARY KEY,
    user_id STRING REFERENCES users(id),
    amount FLOAT,
    type STRING,
    category_id STRING REFERENCES categories(id),
    description STRING,
    date STRING,
    source STRING,
    mpesa_details STRING,
    sms_metadata STRING,
    created_at STRING,
    transaction_group_id STRING,
    transaction_role STRING,
    parent_transaction_id STRING
);

-- ============================================================================
-- BUDGETS TABLE
-- ============================================================================
-- Stores monthly budget allocations per category
CREATE TABLE budgets (
    id STRING PRIMARY KEY,
    user_id STRING REFERENCES users(id),
    category_id STRING REFERENCES categories(id),
    amount FLOAT,
    period STRING,
    month INT,
    year INT,
    created_at STRING
);

-- ============================================================================
-- SMS IMPORT LOGS TABLE
-- ============================================================================
-- Tracks SMS import sessions with statistics
CREATE TABLE sms_import_logs (
    id STRING PRIMARY KEY,
    user_id STRING REFERENCES users(id),
    import_session_id STRING,
    total_messages INT,
    successful_imports INT,
    duplicates_found INT,
    parsing_errors INT,
    transactions_created STRING,
    errors STRING,
    created_at STRING
);

-- ============================================================================
-- DUPLICATE LOGS TABLE
-- ============================================================================
-- Tracks detected duplicate transactions to prevent double-entry
CREATE TABLE duplicate_logs (
    id STRING PRIMARY KEY,
    user_id STRING REFERENCES users(id),
    original_transaction_id STRING,
    duplicate_transaction_id STRING,
    message_hash STRING,
    mpesa_transaction_id STRING,
    reason STRING,
    duplicate_reasons STRING,
    duplicate_confidence FLOAT,
    similarity_score FLOAT,
    detected_at STRING,
    action_taken STRING
);

-- ============================================================================
-- STATUS CHECKS TABLE
-- ============================================================================
-- Health check and system status tracking
CREATE TABLE status_checks (
    id STRING PRIMARY KEY,
    status STRING,
    timestamp STRING,
    details STRING
);

-- ============================================================================
-- SEED DATA: DEFAULT CATEGORIES
-- ============================================================================
-- Insert default categories that all users can use
-- These categories include Kenyan-specific keywords for M-Pesa transaction matching

-- Food & Dining
INSERT INTO categories (id, user_id, name, icon, color, keywords, is_default)
VALUES ('cat-food', NULL, 'Food & Dining', '🍔', '#FF6B6B', '["food", "restaurant", "dining", "lunch", "dinner", "breakfast", "cafe", "hotel", "nyama", "choma", "kfc", "pizza", "java"]', TRUE);

-- Transport
INSERT INTO categories (id, user_id, name, icon, color, keywords, is_default)
VALUES ('cat-transport', NULL, 'Transport', '🚗', '#4ECDC4', '["taxi", "bus", "matatu", "uber", "bolt", "fuel", "parking", "transport", "travel", "petrol", "diesel", "little", "total", "shell"]', TRUE);

-- Shopping
INSERT INTO categories (id, user_id, name, icon, color, keywords, is_default)
VALUES ('cat-shopping', NULL, 'Shopping', '🛍️', '#95E1D3', '["shop", "store", "mall", "clothing", "electronics", "supermarket", "carrefour", "naivas", "quickmart", "tuskys", "chandarana"]', TRUE);

-- Bills & Utilities
INSERT INTO categories (id, user_id, name, icon, color, keywords, is_default)
VALUES ('cat-bills', NULL, 'Bills & Utilities', '📱', '#F38181', '["bill", "electricity", "water", "internet", "phone", "utility", "kplc", "nairobi water", "zuku", "safaricom", "airtel", "telkom", "rent", "dstv", "gotv", "startimes"]', TRUE);

-- Entertainment
INSERT INTO categories (id, user_id, name, icon, color, keywords, is_default)
VALUES ('cat-entertainment', NULL, 'Entertainment', '🎬', '#AA96DA', '["movie", "cinema", "game", "entertainment", "music", "showmax", "netflix", "spotify", "club", "concert", "theater"]', TRUE);

-- Health & Fitness
INSERT INTO categories (id, user_id, name, icon, color, keywords, is_default)
VALUES ('cat-health', NULL, 'Health & Fitness', '⚕️', '#FCBAD3', '["hospital", "pharmacy", "doctor", "medicine", "gym", "health", "clinic", "lab", "dentist", "fitness", "wellness"]', TRUE);

-- Education
INSERT INTO categories (id, user_id, name, icon, color, keywords, is_default)
VALUES ('cat-education', NULL, 'Education', '📚', '#A8D8EA', '["school", "books", "tuition", "education", "course", "university", "college", "training", "fees", "stationary"]', TRUE);

-- Airtime & Data
INSERT INTO categories (id, user_id, name, icon, color, keywords, is_default)
VALUES ('cat-airtime', NULL, 'Airtime & Data', '📞', '#FFFFD2', '["airtime", "data", "bundles", "safaricom", "airtel", "telkom", "faiba", "wifi"]', TRUE);

-- Money Transfer
INSERT INTO categories (id, user_id, name, icon, color, keywords, is_default)
VALUES ('cat-transfers', NULL, 'Money Transfer', '💸', '#FEC8D8', '["transfer", "send money", "mpesa", "paybill", "till", "buy goods", "agent"]', TRUE);

-- Savings & Investments
INSERT INTO categories (id, user_id, name, icon, color, keywords, is_default)
VALUES ('cat-savings', NULL, 'Savings & Investments', '💰', '#957DAD', '["savings", "investment", "deposit", "savings account", "mshwari", "kcb mpesa", "fuliza", "okoa", "equity", "co-op"]', TRUE);

-- Income/Salary
INSERT INTO categories (id, user_id, name, icon, color, keywords, is_default)
VALUES ('cat-income', NULL, 'Income', '💵', '#90EE90', '["salary", "income", "payment", "received", "deposit", "earnings", "wage", "bonus", "commission"]', TRUE);

-- Other
INSERT INTO categories (id, user_id, name, icon, color, keywords, is_default)
VALUES ('cat-other', NULL, 'Other', '📌', '#D4A5A5', '[]', TRUE);

-- ============================================================================
-- INITIALIZATION COMPLETE
-- ============================================================================
-- All tables have been created with proper relationships:
-- 1. users (independent table)
-- 2. categories (independent, user_id is nullable for system categories)
-- 3. transactions (references users and categories)
-- 4. budgets (references users and categories)
-- 5. sms_import_logs (references users)
-- 6. duplicate_logs (references users)
-- 7. status_checks (independent table)
--
-- Default categories have been seeded with Kenyan-specific keywords
-- for intelligent M-Pesa transaction categorization.
--
-- The database is now ready for use!
-- ============================================================================
